// Courtesy of this repo (with some modifications):
// https://github.com/muan/emoji/blob/gh-pages/javascripts/emojilib/simplemap.json

const simpleEmojis = {
  "100": "💯",
  "1234": "🔢",
  "grinning": "😀",
  "grimacing": "😬",
  "grin": "😁",
  "joy": "😂",
  "smiley": "😃",
  "smile": "😄",
  "laughing": "😆",
  "innocent": "😇",
  "wink": "😉",
  "blush": "😊",
  "relaxed": "☺️",
  "yum": "😋",
  "relieved": "😌",
  "kissing": "😗",
  "nerd": "🤓",
  "sunglasses": "😎",
  "hugging": "🤗",
  "smirk": "😏",
  "expressionless": "😑",
  "unamused": "😒",
  "thinking": "🤔",
  "flushed": "😳",
  "disappointed": "😞",
  "worried": "😟",
  "angry": "😠",
  "rage": "😡",
  "pensive": "😔",
  "confused": "😕",
  "persevere": "😣",
  "confounded": "😖",
  "tired": "😫",
  "weary": "😩",
  "triumph": "😤",
  "scream": "😱",
  "fearful": "😨",
  "hushed": "😯",
  "frowning": "😦",
  "anguished": "😧",
  "cry": "😢",
  "sleepy": "😪",
  "sweat": "😓",
  "sob": "😭",
  "dizzy": "😵",
  "astonished": "😲",
  "mask": "😷",
  "sleeping": "😴",
  "zzz": "💤",
  "hankey": "💩",
  "imp": "👿",
  "ogre": "👹",
  "goblin": "👺",
  "skull": "💀",
  "ghost": "👻",
  "alien": "👽",
  "robot": "🤖",
  "cat": "😺",
  "raised hands": "🙌",
  "clap": "👏",
  "wave": "👋",
  "+1": "👍",
  "-1": "👎",
  "facepunch": "👊",
  "fist": "✊",
  "v": "✌️",
  "ok": "👌",
  "hand": "✋",
  "muscle": "💪",
  "pray": "🙏",
  "nail care": "💅",
  "lips": "👄",
  "tongue": "👅",
  "ear": "👂",
  "nose": "👃",
  "eye": "👁",
  "eyes": "👀",
  "speaking head": "🗣",
  "baby": "👶",
  "boy": "👦",
  "girl": "👧",
  "man": "👨",
  "woman": "👩",
  "old man": "👴",
  "old woman": "👵",
  "gua pi mao": "👲",
  "turban": "👳",
  "cop": "👮",
  "construction worker": "👷",
  "guardsman": "💂",
  "sleuth": "🕵",
  "santa": "🎅",
  "angel": "👼",
  "princess": "👸",
  "bride": "👰",
  "runner": "🏃",
  "walking": "🚶",
  "dancer": "💃",
  "dancers": "👯",
  "couple": "👫",
  "bow": "🙇",
  "no good": "🙅",
  "haircut": "💇",
  "massage": "💆",
  "family": "👪",
  "womans clothes": "👚",
  "shirt": "👕",
  "jeans": "👖",
  "necktie": "👔",
  "dress": "👗",
  "bikini": "👙",
  "kimono": "👘",
  "lipstick": "💄",
  "kiss": "💋",
  "footprints": "👣",
  "high heel": "👠",
  "sandal": "👡",
  "boot": "👢",
  "tophat": "🎩",
  "helmet": "⛑",
  "crown": "👑",
  "satchel": "🎒",
  "pouch": "👝",
  "purse": "👛",
  "handbag": "👜",
  "briefcase": "💼",
  "eyeglasses": "👓",
  "dark sunglasses": "🕶",
  "ring": "💍",
  "closed umbrella": "🌂",
  "dog": "🐶",
  "cat": "🐱",
  "mouse": "🐭",
  "hamster": "🐹",
  "rabbit": "🐰",
  "bear": "🐻",
  "panda": "🐼",
  "koala": "🐨",
  "tiger": "🐯",
  "cow": "🐮",
  "pig": "🐷",
  "frog": "🐸",
  "octopus": "🐙",
  "monkey": "🐒",
  "chicken": "🐔",
  "penguin": "🐧",
  "bird": "🐦",
  "chick": "🐤",
  "wolf": "🐺",
  "boar": "🐗",
  "horse": "🐴",
  "unicorn": "🦄",
  "bee": "🐝",
  "bug": "🐛",
  "snail": "🐌",
  "beetle": "🐞",
  "ant": "🐜",
  "spider": "🕷",
  "scorpion": "🦂",
  "crab": "🦀",
  "snake": "🐍",
  "turtle": "🐢",
  "tropical fish": "🐠",
  "fish": "🐟",
  "blowfish": "🐡",
  "dolphin": "🐬",
  "whale": "🐳",
  "crocodile": "🐊",
  "leopard": "🐆",
  "water buffalo": "🐃",
  "ox": "🐂",
  "camel": "🐫",
  "elephant": "🐘",
  "goat": "🐐",
  "ram": "🐏",
  "sheep": "🐑",
  "racehorse": "🐎",
  "rat": "🐀",
  "rooster": "🐓",
  "turkey": "🦃",
  "poodle": "🐩",
  "chipmunk": "🐿",
  "feet": "🐾",
  "dragon": "🐉",
  "cactus": "🌵",
  "christmas tree": "🎄",
  "evergreen tree": "🌲",
  "deciduous tree": "🌳",
  "palm tree": "🌴",
  "seedling": "🌱",
  "herb": "🌿",
  "shamrock": "☘",
  "four leaf clover": "🍀",
  "bamboo": "🎍",
  "tanabata tree": "🎋",
  "leaves": "🍃",
  "fallen leaf": "🍂",
  "maple leaf": "🍁",
  "hibiscus": "🌺",
  "sunflower": "🌻",
  "rose": "🌹",
  "tulip": "🌷",
  "blossom": "🌼",
  "cherry blossom": "🌸",
  "bouquet": "💐",
  "mushroom": "🍄",
  "chestnut": "🌰",
  "jack o lantern": "🎃",
  "shell": "🐚",
  "spider web": "🕸",
  "moon": "🌔",
  "sun": "🌞",
  "star": "⭐",
  "sparkles": "✨",
  "comet": "☄",
  "sunny": "☀️",
  "cloud": "☁️",
  "rain": "🌧",
  "zap": "⚡",
  "fire": "🔥",
  "boom": "💥",
  "snowflake": "❄️",
  "snow": "🌨",
  "snowman": "⛄",
  "snowman with snow": "☃",
  "dash": "💨",
  "tornado": "🌪",
  "fog": "🌫",
  "umbrella": "☔",
  "droplet": "💧",
  "sweat drops": "💦",
  "ocean": "🌊",
  "green apple": "🍏",
  "apple": "🍎",
  "pear": "🍐",
  "tangerine": "🍊",
  "lemon": "🍋",
  "banana": "🍌",
  "watermelon": "🍉",
  "grapes": "🍇",
  "strawberry": "🍓",
  "melon": "🍈",
  "cherries": "🍒",
  "peach": "🍑",
  "pineapple": "🍍",
  "tomato": "🍅",
  "eggplant": "🍆",
  "hot pepper": "🌶",
  "corn": "🌽",
  "sweet potato": "🍠",
  "honey pot": "🍯",
  "bread": "🍞",
  "fried shrimp": "🍤",
  "egg": "🍳",
  "hamburger": "🍔",
  "fries": "🍟",
  "hot dog": "🌭",
  "pizza": "🍕",
  "spaghetti": "🍝",
  "taco": "🌮",
  "burrito": "🌯",
  "ramen": "🍜",
  "stew": "🍲",
  "fish cake": "🍥",
  "sushi": "🍣",
  "bento": "🍱",
  "curry": "🍛",
  "rice": "🍚",
  "rice cracker": "🍘",
  "oden": "🍢",
  "dango": "🍡",
  "shaved ice": "🍧",
  "ice cream": "🍨",
  "icecream": "🍦",
  "cake": "🍰",
  "birthday": "🎂",
  "custard": "🍮",
  "candy": "🍬",
  "lollipop": "🍭",
  "chocolate": "🍫",
  "popcorn": "🍿",
  "doughnut": "🍩",
  "cookie": "🍪",
  "beer": "🍺",
  "beers": "🍻",
  "wine glass": "🍷",
  "cocktail": "🍸",
  "tropical drink": "🍹",
  "bottle": "🍾",
  "sake": "🍶",
  "tea": "🍵",
  "coffee": "☕",
  "baby bottle": "🍼",
  "soccer": "⚽",
  "basketball": "🏀",
  "football": "🏈",
  "baseball": "⚾",
  "tennis": "🎾",
  "volleyball": "🏐",
  "rugby": "🏉",
  "8ball": "🎱",
  "golf": "⛳",
  "golfer": "🏌",
  "table tennis": "🏓",
  "badminton": "🏸",
  "ice hockey": "🏒",
  "field hockey": "🏑",
  "cricket": "🏏",
  "ski": "🎿",
  "skier": "⛷",
  "snowboarder": "🏂",
  "ice skate": "⛸",
  "bow and arrow": "🏹",
  "rowboat": "🚣",
  "swimmer": "🏊",
  "surfer": "🏄",
  "bath": "🛀",
  "weight lifter": "🏋",
  "bicyclist": "🚴",
  "mountain bicyclist": "🚵",
  "horse racing": "🏇",
  "trophy": "🏆",
  "sports medal": "🏅",
  "military medal": "🎖",
  "reminder ribbon": "🎗",
  "rosette": "🏵",
  "ticket": "🎫",
  "art": "🎨",
  "microphone": "🎤",
  "headphones": "🎧",
  "saxophone": "🎷",
  "trumpet": "🎺",
  "guitar": "🎸",
  "violin": "🎻",
  "clapper": "🎬",
  "video game": "🎮",
  "space invader": "👾",
  "dart": "🎯",
  "dice": "🎲",
  "slot machine": "🎰",
  "bowling": "🎳",
  "car": "🚗",
  "taxi": "🚕",
  "bus": "🚌",
  "trolleybus": "🚎",
  "racecar": "🏎",
  "police car": "🚓",
  "ambulance": "🚑",
  "fire engine": "🚒",
  "minibus": "🚐",
  "truck": "🚚",
  "tractor": "🚜",
  "bike": "🚲",
  "train": "🚋",
  "monorail": "🚝",
  "bullettrain": "🚅",
  "steam locomotive": "🚂",
  "metro": "🚇",
  "tram": "🚊",
  "station": "🚉",
  "helicopter": "🚁",
  "airplane": "✈️",
  "departure": "🛫",
  "arrival": "🛬",
  "boat": "⛵",
  "motorboat": "🛥",
  "speedboat": "🚤",
  "ferry": "⛴",
  "rocket": "🚀",
  "seat": "💺",
  "anchor": "⚓",
  "construction": "🚧",
  "fuelpump": "⛽",
  "busstop": "🚏",
  "traffic light": "🚦",
  "checkered flag": "🏁",
  "ship": "🚢",
  "ferris wheel": "🎡",
  "rollercoaster": "🎢",
  "foggy": "🌁",
  "tokyo tower": "🗼",
  "factory": "🏭",
  "fountain": "⛲",
  "mountain": "⛰",
  "volcano": "🌋",
  "japan": "🗾",
  "camping": "🏕",
  "tent": "⛺",
  "national park": "🏞",
  "motorway": "🛣",
  "railway track": "🛤",
  "sunrise": "🌅",
  "desert": "🏜",
  "cityscape": "🏙",
  "stars": "🌠",
  "sparkler": "🎇",
  "fireworks": "🎆",
  "rainbow": "🌈",
  "buildings": "🏘",
  "stadium": "🏟",
  "statue of liberty": "🗽",
  "house": "🏠",
  "office": "🏢",
  "department store": "🏬",
  "post office": "🏣",
  "hospital": "🏥",
  "bank": "🏦",
  "hotel": "🏨",
  "convenience store": "🏪",
  "school": "🏫",
  "wedding": "💒",
  "museum": "🏛",
  "church": "⛪",
  "mosque": "🕌",
  "synagogue": "🕍",
  "kaaba": "🕋",
  "shrine": "⛩",
  "watch": "⌚",
  "iphone": "📱",
  "calling": "📲",
  "computer": "💻",
  "keyboard": "⌨",
  "desktop computer": "🖥",
  "printer": "🖨",
  "trackball": "🖲",
  "joystick": "🕹",
  "compression": "🗜",
  "minidisc": "💽",
  "floppy disk": "💾",
  "cd": "💿",
  "dvd": "📀",
  "vhs": "📼",
  "camera": "📷",
  "phone": "☎️",
  "pager": "📟",
  "fax": "📠",
  "tv": "📺",
  "radio": "📻",
  "hourglass": "⌛",
  "satellite": "📡",
  "battery": "🔋",
  "bulb": "💡",
  "flashlight": "🔦",
  "candle": "🕯",
  "wastebasket": "🗑",
  "oil": "🛢",
  "dollar": "💵",
  "dollars": "💵",
  "yen": "💴",
  "euro": "💶",
  "pound": "💷",
  "moneybag": "💰",
  "credit card": "💳",
  "gem": "💎",
  "scales": "⚖",
  "wrench": "🔧",
  "hammer": "🔨",
  "pick": "⛏",
  "gear": "⚙",
  "chains": "⛓",
  "gun": "🔫",
  "bomb": "💣",
  "hocho": "🔪",
  "shield": "🛡",
  "smoking": "🚬",
  "dead": "☠",
  "coffin": "⚰",
  "amphora": "🏺",
  "barber": "💈",
  "alembic": "⚗",
  "telescope": "🔭",
  "microscope": "🔬",
  "hole": "🕳",
  "pill": "💊",
  "syringe": "💉",
  "thermometer": "🌡",
  "label": "🏷",
  "bookmark": "🔖",
  "toilet": "🚽",
  "shower": "🚿",
  "bathtub": "🛁",
  "key": "🔑",
  "bed": "🛏",
  "door": "🚪",
  "map": "🗺",
  "moyai": "🗿",
  "shopping bags": "🛍",
  "balloon": "🎈",
  "flags": "🎏",
  "ribbon": "🎀",
  "gift": "🎁",
  "tada": "🎉",
  "dolls": "🎎",
  "wind chime": "🎐",
  "crossed flags": "🎌",
  "izakaya lantern": "🏮",
  "envelope": "✉️",
  "incoming envelope": "📨",
  "email": "📧",
  "love letter": "💌",
  "postbox": "📮",
  "mailbox": "📫",
  "package": "📦",
  "postal horn": "📯",
  "inbox": "📥",
  "outbox": "📤",
  "scroll": "📜",
  "date": "📅",
  "calendar": "📆",
  "ballot box": "🗳",
  "file cabinet": "🗄",
  "clipboard": "📋",
  "folder": "📁",
  "rolled up newspaper": "🗞",
  "newspaper": "📰",
  "notebook": "📓",
  "ledger": "📒",
  "books": "📚",
  "book": "📖",
  "link": "🔗",
  "paperclip": "📎",
  "scissors": "✂️",
  "ruler": "📏",
  "pushpin": "📌",
  "lock": "🔒",
  "unlock": "🔓",
  "memo": "📝",
  "pencil2": "✏️",
  "search": "🔍",
  "heart": "❤️",
  "heartbeat": "💓",
  "heartpulse": "💗",
  "cupid": "💘",
  "gift heart": "💝",
  "heart decoration": "💟",
  "peace symbol": "☮",
  "latin cross": "✝",
  "star and crescent": "☪",
  "wheel of dharma": "☸",
  "star of david": "✡",
  "six pointed star": "🔯",
  "menorah": "🕎",
  "yin yang": "☯",
  "orthodox cross": "☦",
  "place of worship": "🛐",
  "ophiuchus": "⛎",
  "aries": "♈",
  "taurus": "♉",
  "gemini": "♊",
  "cancer": "♋",
  "leo": "♌",
  "virgo": "♍",
  "libra": "♎",
  "scorpius": "♏",
  "sagittarius": "♐",
  "capricorn": "♑",
  "aquarius": "♒",
  "pisces": "♓",
  "id": "🆔",
  "atom": "⚛",
  "radioactive": "☢",
  "biohazard": "☣",
  "accept": "🉑",
  "white flower": "💮",
  "ideograph advantage": "🉐",
  "secret": "㊙️",
  "congratulations": "㊗️",
  "ab": "🆎",
  "cl": "🆑",
  "o2": "🅾️",
  "sos": "🆘",
  "no entry": "⛔",
  "name badge": "📛",
  "x": "❌",
  "o": "⭕",
  "anger": "💢",
  "hotsprings": "♨️",
  "no pedestrians": "🚷",
  "do not litter": "🚯",
  "no bicycles": "🚳",
  "underage": "🔞",
  "exclamation": "❗",
  "question": "❓",
  "bangbang": "‼️",
  "interrobang": "⁉️",
  "low brightness": "🔅",
  "high brightness": "🔆",
  "trident": "🔱",
  "fleur de lis": "⚜",
  "warning": "⚠️",
  "children crossing": "🚸",
  "beginner": "🔰",
  "recycle": "♻️",
  "chart": "💹",
  "sparkle": "❇️",
  "cyclone": "🌀",
  "loop": "➿",
  "globe": "🌐",
  "m": "Ⓜ️",
  "atm": "🏧",
  "sa": "🈂️",
  "passport control": "🛂",
  "customs": "🛃",
  "wheelchair": "♿",
  "no smoking": "🚭",
  "wc": "🚾",
  "parking": "🅿️",
  "mens": "🚹",
  "womens": "🚺",
  "restroom": "🚻",
  "cinema": "🎦",
  "signal strength": "📶",
  "koko": "🈁",
  "ng": "🆖",
  "up": "🆙",
  "cool": "🆒",
  "new": "🆕",
  "free": "🆓",
  "fast forward": "⏩",
  "rewind": "⏪",
  "shuffle": "🔀",
  "repeat": "🔁",
  "hash": "#️⃣",
  "information": "ℹ️",
  "symbols": "🔣",
  "musical note": "🎵",
  "notes": "🎶",
  "currency exchange": "💱",
  "copyright": "©️",
  "registered": "®️",
  "tm": "™️",
  "end": "🔚",
  "back": "🔙",
  "on": "🔛",
  "top": "🔝",
  "soon": "🔜",
  "speaker": "🔈",
  "sound": "🔉",
  "mute": "🔇",
  "mega": "📣",
  "loudspeaker": "📢",
  "bell": "🔔",
  "mahjong": "🀄",
  "spades": "♠️",
  "clubs": "♣️",
  "hearts": "♥️",
  "diamonds": "♦️",
  "clock": "🕐",
}
